### PR TITLE
Do not move right when char is not valid for rule

### LINKED ISSUE #331: Move with other pairs
### Description

Using `Rule` the cursor moves independent of the type of ending pair. That is having
``` lua
Rule("$", "$", "markdown"):with_move(conds.done())
```
in the configuration, the cursor is moved with `"`, `)`, etc., even with `(`, which is an opening bracket, while this behavior is expected only with `$`.

### Mapping <cr> bug

nil

### Steps to reproduce

1. Run `nvim -u minimal.lua test.md` to open a new markdown file with a minimal config.
2. Enter insert mode.
3. Type `$a`. The state of the buffer is `$a|$`, where `|` is the cursor. After pressing other ending pair, such as `"` it moves to the state `$a$|`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  local autopairs = require('nvim-autopairs')
  autopairs.setup()
  local Rule = require "nvim-autopairs.rule"
  local conds = require "nvim-autopairs.conds"

  autopairs.add_rule(
    Rule("$", "$", "markdown"):with_move(conds.done())
  )
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by bew**
The issue was that when checking if we should move right, the current char was never checked to be valid for the current rule.

Fixes #331

I didn't manage to run the tests locally, this is why I made many commits & used the CI to test :eyes:

~Only 1 test is failing, and I don't understand why, see the comment below~

### CODE REVIEW

File: tests/nvim-autopairs_spec.lua [hunk 1]
```diff
@@ -169,6 +169,36 @@ local data = {
...
     },
+    {
+        -- ref: issue #331
+        name = "do not move right on non-end-pair char" ,
+        setup_func = function()
+          npairs.add_rule(Rule("$","$"):with_move(cond.done()))
+        end,
+        key    = [[(]],
+        before = [[$|$]],
+        after  = [[$(|)$]]
```
Comment (bew) [inline tests/nvim-autopairs_spec.lua:180]: This test does not pass, I don't understand why..

Adding some debugs, it seems the `can_pair` call of `(` returns `false` in this case, but looking at the code I don't understand why :thinking:

Comment (bew) [reply tests/nvim-autopairs_spec.lua]: That finally explains it, thanks! I used another symbol for that test.

**Comment by bew** [comment]
I rebased this PR for a clean merge if you want.
What do you think?

**Comment by windwp** [comment]
Ok thanks 👍
